server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/no_task_tracker
    username: postgres
    password: 123321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update